In [ ]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [ ]:
import tensorflow as tf
print(tf.constant(6))
print("\n",tf.constant([5,10,13]))
print("\n", tf.constant([[2,3,4]]))
b=tf.Variable([10,27,36])
print("\n Before modyfying",b)
c=b.assign([36,4,5])
print(" \n After modifying",c)


tf.Tensor(6, shape=(), dtype=int32)

 tf.Tensor([ 5 10 13], shape=(3,), dtype=int32)

 tf.Tensor([[2 3 4]], shape=(1, 3), dtype=int32)

 Before modyfying <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 27, 36], dtype=int32)>
 
 After modifying <tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([36,  4,  5], dtype=int32)>


In [ ]:
import tensorflow as tf
b=tf.constant([10,27,36])
print("\n",b)
c=b.assign([36,4,5])
print("After modifying",c)



 tf.Tensor([10 27 36], shape=(3,), dtype=int32)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
import tensorflow as tf
a=tf.ones(7,3)
dtype=tf.int32
print(a)
b=tf.zeros(7)
print(b)
c=tf.fill((3,3),3,6)
print(c)
d=tf.range(4,14,3)
print(d)
print(tf.shape([[4,7,10,13],[8,16,3,4]]))
print(tf.shape([[4,7,10,13]]))
e=tf.constant([2,1,3])
print(type(e))
print(e.ndim)


tf.Tensor([1 1 1 1 1 1 1], shape=(7,), dtype=int32)
tf.Tensor([0. 0. 0. 0. 0. 0. 0.], shape=(7,), dtype=float32)
tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor([ 4  7 10 13], shape=(4,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
1


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(tf.transpose(a)[0])
#print(tf.transpose(a[[1][2]]))
print(a[:,0])
print(a[1:2])
print(a[1:3,0:3])
print(a[0:2,0:3])
print(a[1:3,1:3])
print(a[1:3,0:2])
print(a[0:3,2:3])
print(a[:,2:3])
print(a[::-1])
b=tf.constant([10,20,30])
print(tf.reverse(b,axis=[0]))
c=tf.constant([[10,20,30],[30,80,34]])
print(tf.reverse(c,axis=[0]))
print(tf.reverse(c,axis=[1]))




tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor([10 40 70], shape=(3,), dtype=int32)
tf.Tensor([10 40 70], shape=(3,), dtype=int32)
tf.Tensor([[40 50 60]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[40 50 60]
 [70 80 90]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[50 60]
 [80 90]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[40 50]
 [70 80]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[30]
 [60]
 [90]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[30]
 [60]
 [90]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[70 80 90]
 [40 50 60]
 [10 20 30]], shape=(3, 3), dtype=int32)
tf.Tensor([30 20 10], shape=(3,), dtype=int32)
tf.Tensor(
[[30 80 34]
 [10 20 30]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[30 20 10]
 [34 80 30]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
print(tf.reverse(a,axis=[1,0]))
print(tf.reverse(a,axis=[0,1]))
print(a.shape)
b=tf.constant(([[10,20,30,70,80,90,110,120,130]]))
print(b)
print(b.shape)
c=tf.constant([[10],[20],[30],[70],[80],[90],[110],[120],[130]])
print(c)
print(c.shape)
print(tf.reshape(1,9))


tf.Tensor(
[[130 120 110]
 [ 90  80  70]
 [ 30  20  10]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[130 120 110]
 [ 90  80  70]
 [ 30  20  10]], shape=(3, 3), dtype=int32)
(3, 3)
tf.Tensor([[ 10  20  30  70  80  90 110 120 130]], shape=(1, 9), dtype=int32)
(1, 9)
tf.Tensor(
[[ 10]
 [ 20]
 [ 30]
 [ 70]
 [ 80]
 [ 90]
 [110]
 [120]
 [130]], shape=(9, 1), dtype=int32)
(9, 1)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable