In [4]:
import torch
print(torch.cuda.is_available())

True


In [16]:
import torch
a=torch.tensor([2,4,6,8])
print("\n",torch.tensor(a))
print("\n",a.numel())
print("\n",a.size())
print("\n",a.ndim)
print("\n",a.shape)
print("\n",a.dtype)
print("\n",torch.ones(2,3,dtype=int))#dtype=torch.int32
print("\n",torch.zeros(2,2,dtype=int))




 tensor([2, 4, 6, 8])

 4

 torch.Size([4])

 1

 torch.Size([4])

 torch.int64

 tensor([[1, 1, 1],
        [1, 1, 1]])

 tensor([[0, 0],
        [0, 0]])


/tmp/ipykernel_3876/1172489845.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print("\n",torch.tensor(a))


In [23]:
import torch
a=torch.arange(5,16,2)#range
print("\n",a)
print("\n",torch.randn(3,5))#neg and posi combo
print("\n",torch.rand(3,5))#val b/w 0 and 1





 tensor([ 5,  7,  9, 11, 13, 15])

 tensor([[ 2.0816,  1.6707,  0.3452,  1.2170,  0.9325],
        [ 0.9763,  1.4318,  0.8490, -0.4908, -0.6264],
        [-1.4315, -0.4759, -1.3307, -0.1469,  0.2218]])

 tensor([[0.0497, 0.7525, 0.6751, 0.7737, 0.9862],
        [0.5830, 0.5218, 0.4869, 0.3111, 0.1781],
        [0.2090, 0.5599, 0.6146, 0.0712, 0.5171]])


In [34]:
import torch
a=torch.full((2,3),8)
print("\n",a)



 tensor([[8, 8, 8],
        [8, 8, 8]])


In [53]:
import torch
a=torch.tensor([[18,36,54,78],[36,99,72,8],[24,56,79,3],[1,2,4,5]])
print("\n",a)
print(a[1])
print(a[[2,3]])
print(a[[2,3],2])#by index
print(a[[0,1,2],[1,2,3]])
print(a[[0,1,2],[1,2,3]])
print(a[2:3,1:2])
print(a[2:4,2:4])#by slicing
print(a[2:,2:])
print(a[1:3,1:3])
print(a[-3:-1,-3:-1])


 tensor([[18, 36, 54, 78],
        [36, 99, 72,  8],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([36, 99, 72,  8])
tensor([[24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([79,  4])
tensor([36, 72,  3])
tensor([36, 72,  3])
tensor([[56]])
tensor([[79,  3],
        [ 4,  5]])
tensor([[79,  3],
        [ 4,  5]])
tensor([[99, 72],
        [56, 79]])
tensor([[99, 72],
        [56, 79]])


In [71]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print("\n",torch.add(a,b))
#print("\n",torch.sum(a))#asum()
print("\n",torch.subtract(a,b))
print("\n",torch.multiply(a,b))
print("\n",torch.divide(a,b))
print("\n",torch.mul(a,b))
c=torch.tensor([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("\n",torch.flip(c,dims=[0]))
d=torch.tensor([1,2,11,8,111,89])
print("\n",d.argmax())
print("\n",d.max())
print("\n",torch.max(d))
print("\n",torch.argmax(d))
print("\n",d.argmin())
print("\n",torch.argmin(d))
print("\n",d.min())


 tensor([[ 8, 10, 12],
        [14, 16, 18]])

 tensor([[-6, -6, -6],
        [-6, -6, -6]])

 tensor([[ 7, 16, 27],
        [40, 55, 72]])

 tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])

 tensor([[ 7, 16, 27],
        [40, 55, 72]])

 tensor([[ 7,  8,  9, 10, 11, 12],
        [ 1,  2,  3,  4,  5,  6]])

 tensor(4)

 tensor(111)

 tensor(111)

 tensor(4)

 tensor(0)

 tensor(0)

 tensor(1)


In [75]:
import torch
AI=torch.tensor([40,60,30,70,95])
print(AI>=70)
print(AI[AI>=70])

tensor([False, False, False,  True,  True])
tensor([70, 95])


In [77]:
import torch
AI=torch.tensor([40,60,30,70,95])
print(AI>60)
print(AI[AI>60])

tensor([False, False, False,  True,  True])
tensor([70, 95])
